#!/usr/bin/env bash

set -e

if [ "$#" -ne 1 ]; then
  echo -e "Please provide AUR package name to build\nUsage: docker run --rm -v \$(pwd):/pkg maximbaz/arch-build-aur /bin/bash -c '/build-aur <package-name>'"
  exit 1
fi

package=$1

chown -R makepkg:users /build

sudo -u makepkg git clone --depth 1 https://aur.archlinux.org/"$package".git /build

/build-pkgbuild


cd /pkg

urls=()

json_array() {
  echo -n '['
  while [ $# -gt 0 ]; do
    x=${1//\\/\\\\}
    echo -n \""${x//\"/\\\"}"\"
    [ $# -gt 1 ] && echo -n ', '
    shift
  done
  echo ']'
}


for i in *
do
	/easiest-minio-uploader "$S3_BUCKET" "$i" "$package-$UUID"/"$i"
	urls+=("$S3_HOST/$S3_BUCKET/$package-$UUID/$i")
done	

echo urls

json=$(json_array "${urls[@]}")

curl -XPOST -F "uuid=$UUID" -F "urls=$json" "$MAIN_HOST"/build/complete/mark
