#!/usr/bin/env bash

set -e

if [ "$#" -ne 1 ]; then
  echo -e "Please provide AUR package name to build\nUsage: docker run --rm -v \$(pwd):/pkg maximbaz/arch-build-aur /bin/bash -c '/build-aur <package-name>'"
  exit 1
fi

package=$1

chown -R makepkg:users /build

sudo -u makepkg git clone --depth 1 https://aur.archlinux.org/$package.git /build

/build-pkgbuild

curl $MAIN_HOST/build/complete/mark/$package

cd /pkg

for i in *
do
	curl -X POST -H "Content-Type: application/octet-stream" --data-binary "@$i" $MAIN_HOST/upload\?name=$package
done	
