#!/usr/bin/env bash

set -e

if [ "$#" -ne 1 ]; then
  echo -e "Please provide AUR package name to build\nUsage: docker run --rm -v \$(pwd):/pkg maximbaz/arch-build-aur /bin/bash -c '/build-aur <package-name>'"
  exit 1
fi

package=$1

chown -R makepkg:users /build

sudo -u makepkg git clone --depth 1 https://aur.archlinux.org/"$package".git /build

/build-pkgbuild


cd /pkg

for i in *
do
	env
	/easiest-minio-uploader "$S3_BUCKET" "$i" "$package-$UUID"/"$i"
	curl -F "uuid=$UUID" -F "url=$S3_HOST/$S3_BUCKET/$package-$UUID/$i" "$MAIN_HOST"/build/addURL
done	

curl -XPOST -F "uuid=$UUID" -F "secret=$SECRET" "$MAIN_HOST"/build/complete/mark
